Add recommendations
a-sheryshov/java-filmorate pull request #22
Opened 2023-03-30 15:18 UTC by Alexey-Charushkin

2023-03-30 18:15 UTC, a-sheryshov requested changes
Работа выполнена хорошо!
Есть замечания по гиту
1. Неверно указана ветка слияния (main вместо develop)
2. Нужно сделать сквош промежуточных коммитов.

Рекомендации по коду далее.
Поправь, пожалуйста, id_set на idSet в modelStorage иначе код не пройдет чекстайл
Мой косяк

2023-03-31 05:46 UTC, Alexey-Charushkin commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> -@ComponentScan({"ru.yandex.practicum.filmorate"})
Чек стайл ругался на этот компонент

2023-03-31 05:46 UTC, Alexey-Charushkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/RecommendationDbStorage.java
> +        return result;
Сделано

2023-03-31 05:57 UTC, Alexey-Charushkin commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +    @Autowired
Конструктор из кода убрал. Добавил аннотацию @AllArgsConstructor.  С другими аннотациями конструкторов ломбока зависимости не внедряются (Валяться тесты).

2023-03-31 05:59 UTC, Alexey-Charushkin commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +            log.info("Для пользователя с id {} нет рекомендованных фильмов", userId);
Сделано

2023-03-31 06:04 UTC, Alexey-Charushkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/RecommendationController.java
> +@RequestMapping("/users")
Сделано

2023-03-31 06:05 UTC, Alexey-Charushkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/RecommendationController.java
> +    public List<Film> getRecommendation(@PathVariable Long userId) {
Сделано

2023-03-31 08:04 UTC, a-sheryshov commented
feat: recommendations by Alexey-Charushkin

2023-03-31 08:05 UTC, merged